version: '3'

services:
    db:
        image: postgres
        restart: always
        env_file: ./server/.env
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    redis:
        container_name: redis
        image: redis
        restart: always
        ports:
            - ${REDIS_PORT}:6379

    client:
        depends_on:
            - server
        build:
            context: ./client
        ports:
            - 3000:3000
        environment:
            NEXT_PUBLIC_API_URL: ${API_URL}

    server:
        depends_on:
            - db
            - redis
        build:
            context: ./server
        ports:
            - 5000:5000
        env_file: ./server/.env
        environment:
            CLIENT_URL: ${CLIENT_URL}
            API_URL: ${API_URL}
            PORT: ${PORT}
            AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
            AWS_S3_BUCKET_REGION: ${AWS_S3_BUCKET_REGION}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY_ID: ${AWS_SECRET_ACCESS_KEY_ID}
            SMTP_HOST: ${SMTP_HOST}
            SMTP_PORT: ${SMTP_PORT}
            SMTP_USER: ${SMTP_USER}
            SMTP_PASSWORD: ${SMTP_PASSWORD}
            JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
            JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
            GOOGlE_CLIENT_ID: ${GOOGlE_CLIENT_ID}
            GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
            SESSION_SECRET: ${SESSION_SECRET}
            REDIS_PORT: ${REDIS_PORT}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PORT: ${POSTGRES_PORT}

    nginx:
        container_name: nginx
        image: nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        depends_on:
            - client
            - server

    certbot:
        container_name: certbot
        image: certbot/certbot
        restart: unless-stopped
        command: certonly --webroot -w /var/www/certbot --force-renewal --email vladgeina@gmail.com --agree-tos -d auto-sale.anyeg.me -d api.auto-sale.anyeg.me
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        depends_on:
            - nginx
