version: '3'

services:
    db:
        image: postgres
        restart: always
        env_file: ./server/.env
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - ./pgdata:/var/lib/postgresql/data
    redis:
        container_name: redis
        image: redis
        restart: always
        ports:
            - ${REDIS_PORT}:6379
# run command: docker-compose --env-file server/.env up -d
# build command: docker-compose --env-file server/.env build
# stop command: docker-compose down
